Move classnames module to dependencies
At the moment `classnames` module are in devDependencies. Should be moved to production dependencies, as it's required in a component.

```
Error: Cannot find module 'classnames' from '/www/node_modules/react-responsive-tabs/lib/components'
```